version: '3'
services:
  web:
    image: openmapprimages/openmappr_web:${ENVIRONMENT}
    command: ./run_docker_mode.sh
    restart: unless-stopped
    depends_on:
      - "athena"
      - "elasticsearch"
    ports:
      - "8080:8080"
    volumes:
      - "./server:/usr/src/mappr/server"
    environment:
      - dbHost=${DB_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  athena:
    image: openmapprimages/openmappr_athena:${ENVIRONMENT}
    command: ./run_docker_mode.sh
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - dbHost=${DB_HOST}
    depends_on:
      - "beanstalk"
  beanstalk:
    image: kusmierz/beanstalkd
    restart: unless-stopped
    ports:
      - "11300:11300"
  elasticsearch:
    image: elasticsearch:2.4
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "action.auto_create_index=true"
    ports:
      - "9200:9200"
      - "9300:9300"