version: '3'
services:
  web:
    image: openmapprimages/openmappr_web:${ENVIRONMENT}
    command: ./run_docker_mode.sh
    restart: unless-stopped
    depends_on:
      - "athena"
      - "elasticsearch"
    ports:
      - "8080:8080"
    volumes:
      - "./server:/usr/src/mappr/server"
    environment:
      - DB_HOST=${DB_HOST}
      - EMAIL_TO=${EMAIL_TO}
      - EMAIL_FROM=${EMAIL_FROM}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  athena:
    image: openmapprimages/openmappr_athena:${ENVIRONMENT}
    command: ./run_docker_mode.sh
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - dbHost=${DB_HOST}
    depends_on:
      - "beanstalk"
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/config:/mongo
    command: "/bin/sh -c 'cd /mongo && chmod 777 mongo.sh && ./mongo.sh'"
  beanstalk:
    image: kusmierz/beanstalkd
    restart: unless-stopped
    ports:
      - "11300:11300"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    restart: unless-stopped
    environment:
      - node.name=mappr_prod
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "action.auto_create_index=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300