version: '3'
services:
  athena:
    build: ./athena
    command: ./run_docker_mode.sh
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "mongo"
      - "beanstalk"
  beanstalk:
    image: kusmierz/beanstalkd
    restart: unless-stopped
    ports:
      - "11300:11300"
  mongo:
    build: ./mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
  elasticsearch:
    image: elasticsearch:2.4
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "action.auto_create_index=true"
    ports:
      - "9200:9200"
      - "9300:9300"
