version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        grunt_env: ''
        script_file: 'run_docker_mode'
    command: ./run_docker_mode.sh
    restart: unless-stopped
    depends_on:
      - "athena"
      - "elasticsearch"
    ports:
      - "8080:8080"
    volumes:
      - "./server:/usr/src/mappr/server"
    environment:
      - DB_HOST=${DB_HOST}
      - EMAIL_TO=${EMAIL_TO}
      - EMAIL_FROM=${EMAIL_FROM}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  athena:
    build: ./athena
    command: ./run_docker_mode.sh
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "mongo"
      - "beanstalk"
  beanstalk:
    image: kusmierz/beanstalkd
    restart: unless-stopped
    ports:
      - "11300:11300"
  mongo:
    build: ./mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    restart: unless-stopped
    environment:
      - node.name=mappr_prod
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "action.auto_create_index=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
